### PR TITLE
[RFR] Fix debugger if constant is an array

### PR DESCRIPTION
**Pull request by KazuAlex**
I have this error

2020-01-22-141928_1059x1663_scrot

This PR fix it

2020-01-22-142706_1073x817_scrot

### CODE REVIEW

**Comment by jdecool** [comment]
Hi @KazuAlex,

Thanks for this work.

Could you rebase you branch with the branch `1.4` to fix this issue for symfony `3.4` & `4.*` ?

After that, your code will be merge in the `master` branch.

**Comment by KazuAlex** [comment]
Hi @jdecool 

I've rebased from 1.4 branch.

**Comment by jdecool** [comment]
:+1: Thanks I will merge it tonight

**Comment by jdecool** [comment]
Integrated in the `1.4` branch via a cherry-pick a8b70a0988828d613f713c33eca08cfacf2929bf.

Just tag version [1.4.2](https://github.com/jdecool/TwigConstantAccessorBundle/releases/tag/1.4.2) and [1.5.2](https://github.com/jdecool/TwigConstantAccessorBundle/releases/tag/1.5.2).

Thanks for your contribution.

**Pull request closed without merging**
