### PR TITLE
[RFR] Fix data collector "reset()" function unimplemented

### PR DESCRIPTION
**Pull request by KazuAlex**
Fix this error :

```
Error: Class JDecool\Bundle\TwigConstantAccessorBundle\DataCollector\ConstantCollector contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Symfony\Contracts\Service\ResetInterface::reset)
```

Stack trace :
```
class JDecool\Bundle\TwigConstantAccessorBundle\DataCollector\ConstantCollector extends DataCollector
```
=>
```
abstract class Symfony\Component\HttpKernel\DataCollector\DataCollector implements DataCollectorInterface
```
=>
```
interface Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface extends ResetInterface
```
=>
```
interface Symfony\Contracts\Service\ResetInterface
{
    public function reset();
}
```

### CODE REVIEW

**Comment by KazuAlex** [comment]
All the two jobs fail are about memory size :

**Travis**
```
Updating dependencies (including require-dev)

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 268435456 bytes) in phar:///home/travis/.phpenv/versions/5.6.40/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 268435456 bytes) in phar:///home/travis/.phpenv/versions/5.6.40/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.The command "composer update --prefer-dist --no-interaction $COMPOSER_FLAGS" failed and exited with 255 during .

Your build has been stopped.
```

**Scrutinizer**
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
[....]
  - Installing sebastian/exporter (3.1.2)
    Cloning 68609e1261d215ea5b21b7987539cbfbe156ec3e
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/bin...', 954, Array)
#1 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object in phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php on line 954

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/bin...', 954, Array)
#1 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object in phar:///usr/bin/composer.phar/vendor/symfony/console/Application.php on line 954
```

@jdecool any idea ?

**Comment by jdecool** [comment]
Hi @KazuAlex,

Thanks for your fix.

Travis-CI and Scrutinizer errors seems to be caused by an insufficient PHP memory limit.

To fix the Travis build, execute Composer with memory limit by updating the install command by `install: php -d memory_limit=-1 composer update --prefer-dist --no-interaction $COMPOSER_FLAGS`.

For Scrutinizer, try to add the lines below at the end of the `.scrutinizer.yml` :

```yaml
environment:
    ini:
        memory_limit: "-1"
```

**Comment by KazuAlex** [comment]
Hi @jdecool 
Tests fixed ! :)

**Review by jdecool — APPROVED** [review]

**Comment by KazuAlex** [comment]
@jdecool , can you make a 1.4.1 release for packagist ?

**Comment by jdecool** [comment]
:heavy_check_mark: https://github.com/jdecool/TwigConstantAccessorBundle/releases/tag/1.4.1

**Pull request merged**
